### ISSUE TITLE
Double model enumeration

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingcon#58] opened 2021-03-16 11:21 UTC
In the branch: [bugnondeter](https://github.com/potassco/clingcon/tree/bugnondeter) the testcase fs/fso fails non-deterministically.
`test_clingcon fs -c fso`

Sometimes, some models are enumerated several times.
This bug is only triggered using multi-shot solving, multithreading (at least two threads) with at least one thread using `usc` (using optimization) and only with a new clingcon feature that (in the case of the testcase) pretranslates exactly one constraint per mutishot step.
See this [ci action](https://github.com/potassco/clingcon/actions/runs/657350641) where some of the builds fail.

I built a [clasp version](https://github.com/MaxOstrowski/clasp/tree/dev) that helps with serializing and replaying clasp, maybe this is of some help.

@rkaminsk

**Comment by rkaminsk** [comment] 2021-03-16 23:52
Hello Max, it looks like with `--learn-explicit` and `--distribute=no` the bug is still triggered and nondeterminism from clause exchange should be gone. With this, it should be enough to ensure that the `UncoreMinimize::handleUnsat` and `UncoreMinimize::handleModel` (and maybe `UncoreMinimize::integrate` are called in the right order). To ensure that there are no deadlocks, a lock has to be taken before clasp takes its model lock.

**Comment by MaxOstrowski** [comment] 2021-03-17 09:07
Thanks for looking into it. Ordering these 3 calls unfortunately seems not enough.
A deadlock happens during the "retrace" phase, as another order is chosen by clasp. Some more non-determinism takes place somewhere else ... :cry:

**Comment by rkaminsk** [comment] 2021-03-17 10:49
Like I said you have to lock clasp's on_model call at the right place. I quickly skimmed your code but could not find it. Grep for lock_guard to find it. Otherwise, you will get dead locks...

Candidates:
- `ParallelSolve::commitModel`

**Comment by MaxOstrowski** [comment] 2021-03-17 11:54
Updated my [clasp dev](https://github.com/MaxOstrowski/clasp/tree/dev) version.
My locks (hopefully) allow for recursive locking of 1 thread now (as `ParallelSolve::commitModel` calls `UncoreMinimize::handleModel`).
The retrace behaviour is still non-deterministic.

**Comment by rkaminsk** [comment] 2021-03-17 13:22
> The retrace behaviour is still non-deterministic.

I think that now it is just about placing some more locks in the right places. Anything that uses atomics and locks is a candidate. With your setup, it should be quite easy to experiment a bit.

**Comment by MaxOstrowski** [comment] 2021-03-22 13:13
I have a working setup now.
Given the clingcon branch:
https://github.com/potassco/clingcon/tree/bugnondeter
The following unit case
`test_clingcon fs -c fso`
fails non-deterministically (models are enumerated several times).

Given clingcon compiled with this serialized clasp branch
https://github.com/MaxOstrowski/clasp/tree/dev
and the (unpacked) 
[trace.zip](https://github.com/potassco/clingcon/files/6182355/trace.zip)
file in the calling directory, this error occurs deterministically.

(The serialized clasp branch creates a `trace` file if not existing. If the file exists, the order of the calls in the trace file is replayed. Note that not every created `trace` file is deadlock free. The attached file worked in 100/100 runs to fail the unit test and does not deadlock. No guarantees though.)

**Comment by rkaminsk** [comment] 2021-03-22 13:48
I had to add the file `locker.cpp` to the source files to compile. Are you sure you checked everything in? When I run with your trace file, then it hangs right in the beginning:
```
./build/debug/bin/test_clingcon fs -c fso
Filters: fs
ClaspFacade::initBuilder
Create Locker
Replay mode (trace file found)
**HANG**
```

**Comment by MaxOstrowski** [comment] 2021-03-22 14:09
Sorry, messed up the clasp commit somehow.
Should work now.
You just have to have the trace file in your directoy (you call shows "replay mode" so everything should work).
Please try with the updated clasp branch, I forgot to commit changes and lock steps apparently ....

**Comment by rkaminsk** [comment] 2021-03-22 14:34
With the update clasp I can now sometimes reproduce the error but sometimes it also hangs.

**Comment by MaxOstrowski** [comment] 2021-03-22 15:42
I let it ran again for 1000 runs and had exactly 1 deadlock (it hangs). So I do not know how to get rid of this.
Whats the percentage rate on your side?

I double checked the versions, i have
clingcon: branch bugnondeter
clingo: 7a27ce819feda3c2ee33a5ac622ac57106f47797 (3 commits below dev version)
clasp: branch https://github.com/MaxOstrowski/clasp/tree/dev

I have to check if updating clingo changes anything ...

**Comment by BenKaufmann** [comment] 2021-04-18 16:05
@rkaminsk @MaxOstrowski 
Sorry, I somehow (automatically) closed this ticket. Probably due to my commit message in clasp. While I definitely fixed a problem, I only tested against @rkaminsk minimal example. Please check for yourself whether the issue is really fixed.

**Comment by rkaminsk** [comment] 2021-04-19 20:22
Since it seems to work, I am closing this.

**Closed by rkaminsk** 2021-04-19 20:22 UTC
Labels: bug
